### ISSUE TITLE
CNAbstractController Stops working when camera is moved.

### ISSUE THREAD

**Issue by rapito** [KumoKairo/CNJoystick#4]
Following the unity3d [roll-a-ball](http://portalpsp/oms-direccionesPlus/services/SadService?wsdl) tutorial, adding the [*CameraController Script*](https://github.com/rapito/unity-roll-a-ball/blob/master/Assets/Scripts/CamController.cs) to the **CNControlCamera** causes the **CNAbstractController** to stop working after the camera follows the player.  

My guess is that one must manually update some reference vector used for managing input, haven't had the time to check it though...

For it to work again the player must be on the camera starting position.
i.e:

- Player moves from (0,0,0) to (10,0,0) using the **CNJoystick**.
- Camera automatically follows player accordingly. (CNJoystick UI moves and shows correctly).
- **CNAJoystick** does not longer responds to input.
- Player moves from (10,0,0) to (0,0,0) using Keyboard Input.
- **CNAJoystick** works again.

**Comment by KumoKairo** [comment]
It's stated in a readme that you should not use CN Camera as a game camera. It's should remain stationary throughout the game
The overhead of the second camera is far less than of recalculating the position of controls every frame
